# Generated by Django 4.1.4 on 2023-10-28 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('prob_id', models.AutoField(primary_key=True, serialize=False)),
                ('prob_title', models.CharField(max_length=50)),
                ('prob_desc', models.TextField()),
                ('prob_diff', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('prob_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('verdict', models.CharField(max_length=5)),
                ('prob_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.problem')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
