# Generated by Django 4.1.4 on 2024-01-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='test_in',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_out',
            field=models.TextField(default=1),
        ),
    ]
